### ISSUE TITLE
需要目录跟随文章滚动高亮

### ISSUE THREAD

**Issue by yixvan6** [Yue-plus/hexo-theme-arknights#1]
看能不能在文章展示页面在右侧只显示TOC

**Comment by Yue-plus** [comment]
已收到反馈 `( ° ▽、° ) `

**Comment by Yue-plus** [comment]
**BUG 已修复，感谢反馈。**
现在右侧边栏是单独滚动的。
预览：《[这是一篇拥有很长目录的文章](https://ark.theme.yueplus.ink/2020/04/12/longindex/)》
> 没有更新的话可以按 `Ctrl` + `F5` 强制刷新页面。

另外，添加了 Valine 评论系统。可以试试~

**Comment by Yue-plus** [comment]
现在可以修改主题配置文件 `_config.yml`
```yml
aside:
  block_in_top: true
```
来把文章页 toc 目录置顶了~~

**Comment by yixvan6** [comment]
:+1:  如果能随着文章的滑动，目录跟着自动高亮就更好了

**Comment by Yue-plus** [comment]
> 👍 如果能随着文章的滑动，目录跟着自动高亮就更好了

[以加入计划任务](https://github.com/Yue-plus/hexo-theme-arknights/projects/1#card-36699195)

**Comment by Yue-plus** [comment]
目录现在会随文章滚动高亮了~~
