### ISSUE TITLE
请问如何设置文章封面

### ISSUE THREAD

**Issue by Syaoran33** [Yue-plus/hexo-theme-arknights#126]
在文章frontmatter中添加cover和backgroud没有效果
`
cover: /img/cover.jpg
background: /img/cover.jpg
`
参考文档中好像没有说明，请问下如何配置文章封面图片

**Comment by Yue-plus** [comment]
在 `<!-- more -->` 之前的内容称之为摘要，会显示在首页上，并且可以设置是否也在正文显示。

示例网站的 .md 文件都在 [hexo 分支里](https://github.com/Yue-plus/hexo-theme-arknights/tree/hexo/source/_posts)，可以参考下

**Comment by Syaoran33** [comment]
好的 感谢
