### ISSUE TITLE
gitalk评论不显示

### ISSUE THREAD

**Issue by ark2005** [Yue-plus/hexo-theme-arknights#127]
如图，我已经设置了gitalk的相关内容，但在hexo博客上不显示，这该怎么解决，谢谢
![image](https://github.com/Yue-plus/hexo-theme-arknights/assets/57824374/432ca488-c1d2-43f3-8993-d43e9bf9fa85)

**Comment by Yue-plus** [comment]
`gitalk.id` 没有被设置，默认为 `location.pathname`

抱歉这是一个小失误，默认配置文件没有默认值。
现在已经修复，请拉取 `main` 分支更新。

----------

另外，示例网站也添加了一个 Gitalk 的示例 [点击查看](https://arknights.theme.hexo.yue.zone/2020/04/19/nihonngo/)。

另另外，其他示例网站配置文件在 [hexo 分支的 `_config.arknights.yml`](https://github.com/Yue-plus/hexo-theme-arknights/blob/hexo/_config.arknights.yml)

**Comment by ark2005** [comment]
解决了，非常感谢
