### ISSUE TITLE
怎么为一个文章添加多个标签

### ISSUE THREAD

**Issue by nicemist** [Yue-plus/hexo-theme-arknights#139]
怎么为一个文章添加多个标签

**Comment by Yue-plus** [comment]
```markdown
---
tags:
- tag1
- tag2
- tag3
---
```

或者：

```markdown
---
tags: [tag1, tag2, tag3]
---
```

参考：
- [Front-matter | Hexo](https://hexo.io/zh-cn/docs/front-matter)
- [YAML 入门教程 | 菜鸟教程](https://www.runoob.com/w3cnote/yaml-intro.html)

**Comment by nicemist** [comment]
解决
