### ISSUE TITLE
new新文章的时候怎么生成一个文件夹

### ISSUE THREAD

**Issue by nicemist** [Yue-plus/hexo-theme-arknights#140]
我想要的：hexo new test
在post文件夹里面生成一个test文件夹，里面有test.md

**Comment by Yue-plus** [comment]
我猜测你可能是想要自定义布局；请参考 Hexo 官方文档：[写作 - 布局](https://hexo.io/zh-cn/docs/writing#%E5%B8%83%E5%B1%80%EF%BC%88Layout%EF%BC%89) | [`new` 指令](https://hexo.io/zh-cn/docs/commands#new)
