### ISSUE TITLE
[bug?]多行公式渲染

### ISSUE THREAD

**Issue by sjfhsjfh** [Yue-plus/hexo-theme-arknights#145]
```Markdown
$$
\begin{aligned}
\mathrm{d} \mu =& \frac{\partial}{\partial T} \frac{\partial G}{\partial n} \mathrm{d}T + \frac{\partial}{\partial p} \frac{\partial G}{\partial n} \mathrm{d}p \\
=& \frac{\partial}{\partial n} \frac{\partial G}{\partial T} \mathrm{d}T + \frac{\partial}{\partial n} \frac{\partial G}{\partial p} \mathrm{d}p
\end{aligned}
$$
```

$$
\begin{aligned}
\mathrm{d} \mu =& \frac{\partial}{\partial T} \frac{\partial G}{\partial n} \mathrm{d}T + \frac{\partial}{\partial p} \frac{\partial G}{\partial n} \mathrm{d}p \\
=& \frac{\partial}{\partial n} \frac{\partial G}{\partial T} \mathrm{d}T + \frac{\partial}{\partial n} \frac{\partial G}{\partial p} \mathrm{d}p
\end{aligned}
$$

在博客中不多行显示, landscape 主题也有同样行为, 推测为 hexo bug

**Comment by ToUNVRSe** [comment]
被 markdown 渲染转义了，可写 `////` 或者使用 hexo-renderer-pandoc
