### ISSUE TITLE
url no found报错

### ISSUE THREAD

**Issue by AtalKaslana** [Yue-plus/hexo-theme-arknights#163]
<img width="1280" alt="32b0aa3e607e9f833f8e06babc75b46a" src="https://github.com/Yue-plus/hexo-theme-arknights/assets/136092353/a485ac96-24d0-40d5-8bb0-5c249ea40f5a">
请问在部署初始化时无法发现主题url问题应该怎么解决？

**Comment by Yue-plus** [comment]
这个是没有找到主题文件夹，请把工作流配置文件发上来看看
