### ISSUE TITLE
对Gitalk插件的布局好像有问题

### ISSUE THREAD

**Issue by LongFengShuanWu** [Yue-plus/hexo-theme-arknights#169]
我在博客部署了Gitalk之后显示的评论区布局很奇怪
![屏幕截图 2024-08-15 150945](https://github.com/user-attachments/assets/051b63de-0999-46d5-9a99-2acdcf2ab0fb)
![屏幕截图 2024-08-15 150929](https://github.com/user-attachments/assets/538dc1d7-4394-424d-9068-f86428cd96fe)

我的博客链接：
https://blog.yuanli-lfsw.com/2024/08/11/PositronJMBom%E8%A1%A8/

**Comment by Yue-plus** [comment]
可能是因为网络原因部分 css 样式表没有获取到，多刷新几次即可。

![image](https://github.com/user-attachments/assets/205ded34-56be-47ab-bb39-9037788de846)
![image](https://github.com/user-attachments/assets/abf05702-e369-47b7-8b08-22bac307475d)

**Comment by LongFengShuanWu** [comment]
好的，看来我这边的网络不咋的，现在可以了
