### ISSUE TITLE
gitalk窗口有时出现一次只能打一个字的情况

### ISSUE THREAD

**Issue by Abyss-Seeker** [Yue-plus/hexo-theme-arknights#170]
挺玄学的，比如我的Edge浏览器就只能一次打一个字（然后就会自动退出那个文本框），删除了缓存还是会；但我重新开个incognito就不会有这样的问题。

**Comment by Yue-plus** [comment]
可能是由于 pjax 功能引起的 Bug；
请尝试编辑 [`_config.arknights.yml`](https://github.com/Yue-plus/hexo-theme-arknights/blob/hexo/_config.arknights.yml#L123) 文件，禁用 pjax

```yml
# pjax 支持
pjax:
  enable: false
```

看看这个问题是否任然存在。
期待你的回复。

**Comment by Abyss-Seeker** [comment]
哇，好快的回复！我去试试

**Comment by Abyss-Seeker** [comment]
似乎还是有问题。。我刚localhost上预览了一下。但有意思的是依旧是正常microsoft edge会出这个bug但是开了incognito隐私模式窗口以后不会有

**Comment by Abyss-Seeker** [comment]
的确还是不行

**Comment by Yue-plus** [comment]
你是只在使用 `hexo server` 的情况下出现这个问题吗？
也有可能是 [`hexo-browsersync`](https://github.com/hexojs/hexo-browsersync) 依赖造成的，应该不会影响部署。
可以先部署一个静态站点试试还存在这个问题。

> 这个依赖是为 `hexo server` 提供热更新的；
> 已知会照成长文章显示不全的问题，但不会影响部署；

------------------------------------------------

另外请提供一下 Hexo 目录的 [package.json](https://github.com/Yue-plus/hexo-theme-arknights/blob/hexo/package.json) 文件。

**Comment by Abyss-Seeker** [comment]
我刚试了一下，的确是hexo server下才会有的问题。
Hexo/package.json
`
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "7.3.0"
  },
  "dependencies": {
    "hexo": "^7.3.0",
    "hexo-browsersync": "^0.3.0",
    "hexo-deployer-git": "^4.0.0",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^4.0.0",
    "hexo-generator-tag": "^2.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^6.3.0",
    "hexo-renderer-pug": "^3.0.0",
    "hexo-renderer-stylus": "^3.0.1",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^1.0.0"
  }
}

`

**Comment by Abyss-Seeker** [comment]
在大佬您的站里面那个
https://arknights.theme.hexo.yue.zone/2020/04/19/nihonngo/
试了一下，发现Valine的没问题，但是gitalk的只能一次打一个字

**Comment by Yue-plus** [comment]
这太奇怪了，我这边无法复现这个问题；
你能换一个浏览器在 [示例站点](https://arknights.theme.hexo.yue.zone/2020/04/19/nihonngo/) 试试吗？

也有可能是你的浏览器拓展插件导致了这个问题。请试试禁用所有拓展插件试试是否任然存在这个问题。

**Comment by Yue-plus** [comment]
> 静态站点部署后也还是有这个问题，我刚用http-server public也试了一下，依旧是只能一次打一个字（神奇

能提供一下已部署站点的链接吗？

**Comment by Abyss-Seeker** [comment]
https://itsuyo.top/2024/09/06/hello-world/

**Comment by Abyss-Seeker** [comment]
> 这太奇怪了，我这边无法复现这个问题； 你能换一个浏览器在 [示例站点](https://arknights.theme.hexo.yue.zone/2020/04/19/nihonngo/) 试试吗？
> 
> 也有可能是你的浏览器拓展插件导致了这个问题。请试试禁用所有拓展插件试试是否任然存在这个问题。

发生了有意思的事，一开始的时候可以连续打，几秒钟后加载完毕了就只能一次一个字了。我怀疑的确可能是什么插件的问题，我一个个关了试试

**Comment by Abyss-Seeker** [comment]
破案了，grammarly插件

**Comment by Yue-plus** [comment]
😂

好的，如果没有其他问题的话请关闭这个 Issue

**Comment by Abyss-Seeker** [comment]
非常感谢！
似乎grammarly会专门和gitalk哪里会产生冲突。。。
