### ISSUE TITLE
增加404页面的支持

### ISSUE THREAD

**Issue by feilongproject** [Yue-plus/hexo-theme-arknights#20]
RT，在用github pages等静态页面托管时，如果链接404了，可以直接导航到网站主页或者上一页，而不是用着默认的页面

**Comment by Yue-plus** [comment]
感谢反馈，已加入[计划任务](https://github.com/Yue-plus/hexo-theme-arknights/projects/1#card-45355532)

**Comment by Yue-plus** [comment]
已添加 `404.html` 文件
预览 <https://ark.theme.yueplus.ink/adad>

![image](https://user-images.githubusercontent.com/33195150/93078883-d5890500-f6bd-11ea-86b0-a22b71a4fcd2.png)
![image](https://user-images.githubusercontent.com/33195150/93078921-e2a5f400-f6bd-11ea-89ce-26a19bc36b8c.png)

**Comment by Yue-plus** [comment]
注意，GitHub Page 需要绑定域名才能使用自定义 404 页面。
