### ISSUE TITLE
建议增加mermaid绘图支持

### ISSUE THREAD

**Issue by Laurenfrost** [Yue-plus/hexo-theme-arknights#22]
RT，这样就能在博客直接插入流程图、甘特图等等，无需转成图片，方便后续修改
https://github.com/mermaid-js/mermaid

**Comment by Yue-plus** [comment]
感谢反馈，已添加支持。[点击预览](https://ark.theme.yueplus.ink/2020/04/15/markdown/#%E6%B5%81%E7%A8%8B%E5%9B%BE)

请从 `master` 分支拉取更新。

![QQ截图20201023153155](https://user-images.githubusercontent.com/33195150/96969339-ee9a9680-1544-11eb-9ee7-1d23504f933e.jpg)
