### ISSUE TITLE
希望增加文章加密功能

### ISSUE THREAD

**Issue by zsq259** [Yue-plus/hexo-theme-arknights#23]
如题

**Comment by Yue-plus** [comment]
可以试试 [hexo-blog-encrypt](https://github.com/D0n9X1n/hexo-blog-encrypt/blob/master/ReadMe.zh.md)

**Comment by Yue-plus** [comment]
还可以参考：
> - [APACHE密码设置 - justcoder - 博客园](https://www.cnblogs.com/justneedwater/archive/2010/12/10/1902052.html)
> - [基于nginx的配置网站密码认证 - 启云 - 博客园](https://www.cnblogs.com/eeexu123/p/9243298.html)

**Comment by MaxLiu245** [comment]
> 可以试试 [hexo-blog-encrypt](https://github.com/D0n9X1n/hexo-blog-encrypt/blob/master/ReadMe.zh.md)

实测用 `hexo-blog-encrypt@3.1.6` 时本地预览不显示密码输入框，没想明白原因。以前用 `Next` + `hexo-blog-encrypt@3.0.12` 没有问题，所以试着回退了版本，但还是同样的问题。查别的 `issue` 也没有查到类似的情况

![password-error](https://user-images.githubusercontent.com/36635379/148902899-dc7934e4-1d8e-4a90-9a78-38dbdb1b9f77.png)

**Comment by Yue-plus** [comment]
> > 可以试试 [hexo-blog-encrypt](https://github.com/D0n9X1n/hexo-blog-encrypt/blob/master/ReadMe.zh.md)
> 
> 实测用 `hexo-blog-encrypt@3.1.6` 时本地预览不显示密码输入框，没想明白原因。以前用 `Next` + `hexo-blog-encrypt@3.0.12` 没有问题，所以试着回退了版本，但还是同样的问题。查别的 `issue` 也没有查到类似的情况
> 
> ![password-error](https://user-images.githubusercontent.com/36635379/148902899-dc7934e4-1d8e-4a90-9a78-38dbdb1b9f77.png)

这是一个待解决的已知问题（这也是为什么这个 issue 一直开着，并且 [`README.md`](https://github.com/Yue-plus/hexo-theme-arknights#readme) 里关于文档加密的部分被注释 Orz

**Comment by ReadER-L** [comment]
这个问题解决了吗

**Comment by Yue-plus** [comment]
> 这个问题解决了吗

待解决，欢迎PR。

**Comment by Yue-plus** [comment]
> 这个问题解决了吗

主题已更新，此问题已解决，请参照 [更新指引](https://github.com/Yue-plus/hexo-theme-arknights/releases/tag/1.14.0) 升级主题

Demo：[加密文档（密码：yueplus）](https://ark.theme.yueplus.ink/2020/12/01/encrypt/)
