### ISSUE TITLE
自己的问题：文章下面的next 跳转错误，怎么解决

### ISSUE THREAD

**Issue by madisontanle** [Yue-plus/hexo-theme-arknights#24]
![image](https://user-images.githubusercontent.com/46909580/104835487-f36fac00-58e1-11eb-8e33-873f0158b5de.png)
![image](https://user-images.githubusercontent.com/46909580/104835493-fcf91400-58e1-11eb-8057-1503ae18fa7d.png)

**Comment by madisontanle** [comment]
看了其他人的主题，这里都可以正常运行

**Comment by Yue-plus** [comment]
可以把 Hexo 目录下的 `_config.yml` 文件 和 `package.json` 文件贴上来看看吗？

**Comment by madisontanle** [comment]
[https://github.com/madisontanle/madisontanle.github.io](url)

**Comment by madisontanle** [comment]
https://github.com/madisontanle/madisontanle.github.io

**Comment by madisontanle** [comment]
链接：https://pan.baidu.com/s/1aCs9SROZKkqSjp3Fiqz8Gg 
提取码：1234

**Comment by Yue-plus** [comment]
抱歉，这应该算是我的锅。
现在更新到了 [hexo-theme-arknights_1.2.1](https://github.com/Yue-plus/hexo-theme-arknights/releases/tag/1.2.1)
> ~~三个月没更新 Release~~ `/(ㄒoㄒ)/~~`

**Comment by madisontanle** [comment]
好滴
