### ISSUE TITLE
请问这是啥报错？

### ISSUE THREAD

**Issue by HUSTJunshuang** [Yue-plus/hexo-theme-arknights#25]
![image](https://user-images.githubusercontent.com/66196600/119252208-82b50500-bbdd-11eb-8cc2-a14afaadaab5.png)

**Comment by Yue-plus** [comment]
不用在意这个错误，这个错误不影响使用

**Comment by HUSTJunshuang** [comment]
嗯，刚刚试了一下，确实没问题，因为我之前在Linux上搭建的时候不兼容，也有很多类似的报错，所以我以为有这报错用不了。谢谢大佬！
