### ISSUE TITLE
error TS2305

### ISSUE THREAD

**Issue by itlubber** [Yue-plus/hexo-theme-arknights#26]
# 启动之后一直报错，不知道是为什么QAQ
```
>> hexo s                                                                                                                                                                                                  
INFO  Validating config
INFO  Start processing
[Browsersync] Access URLs:
 ----------------------------------
          UI: http://localhost:3001
 ----------------------------------
 UI External: http://localhost:3001
 ----------------------------------
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
ERROR node_modules/_@types_babel-types@7.0.9@@types/babel-types/index.d.ts(10,15): error TS2307: Cannot find module './ts3.6/index' or its corresponding type declarations.
。。。
ERROR node_modules/_@types_babel-types@7.0.9@@types/babel-types/index.d.ts(244,109): error TS2307: Cannot find module './ts3.6/index' or its corresponding type declarations.
ERROR node_modules/_@types_babylon@6.16.5@@types/babylon/index.d.ts(8,10): error TS2305: Module '"./node_modules/@types/babel-types"' has no exported member 'File'.
ERROR node_modules/_@types_babylon@6.16.5@@types/babylon/index.d.ts(8,16): error TS2305: Module '"./node_modules/@types/babel-types"' has no exported member 'Expression'.
```

**Comment by Yue-plus** [comment]
这个报错不影响使用⊙ω⊙



---Original---
From: ***@***.***&gt;
Date: Wed, Jun 30, 2021 00:29 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Yue-plus/hexo-theme-arknights] error TS2305 (#26)




 
启动之后一直报错，不知道是为什么QAQ
   
hexo s                                                                                                                                                                                                 
 INFO  Validating config
 INFO  Start processing
 [Browsersync] Access URLs:
   
       UI: http://localhost:3001  
 
UI External: http://localhost:3001
 
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
 ERROR ***@***.******@***.***@@types/babel-types/index.d.ts(10,15): error TS2307: Cannot find module './ts3.6/index' or its corresponding type declarations.
 。。。
 ERROR ***@***.******@***.***@@types/babel-types/index.d.ts(244,109): error TS2307: Cannot find module './ts3.6/index' or its corresponding type declarations.
 ERROR ***@***.******@***.***@@types/babylon/index.d.ts(8,10): error TS2305: Module ***@***.***/babel-types"' has no exported member 'File'.
 ERROR ***@***.******@***.***@@types/babylon/index.d.ts(8,16): error TS2305: Module ***@***.***/babel-types"' has no exported member 'Expression'.

**Comment by Yue-plus** [comment]
已修复
