### ISSUE TITLE
Mermaid FAIL

### ISSUE THREAD

**Issue by ToUNVRSe** [Yue-plus/hexo-theme-arknights#27]
Mermaid 反复提示语法错误，直接复制样例都挂了 QAQ

另外这个 Mermaid 没更新欸。

**Comment by Yue-plus** [comment]
Mermaid 现已更新到 `8.11.0`，可在主题目录下执行 `git pull` 更新主题。

另外，我这边没有报语法错误，可否提供一些报错截图或样例仓库？

我的样例：
- [页面样例](https://ark.theme.yueplus.ink/mermaid/)
- [源文件样例](https://github.com/Yue-plus/hexo-theme-arknights/blob/hexo/source/_posts/mermaid.md)

**Comment by ToUNVRSe** [comment]
@Yue-plus 谔谔，经过一堆魔改之后找到问题了，mermaid 所有的非语法行末尾要加分号

另外请教一个问题：我试图去掉备案信息的时候发现 theme.stylesheets !== undefined && theme.stylesheets.length > 0 这种判断根本不生效 QWQ ，没有对应项直接就语法错误了……鄙人 OIer 只会 CPP ，自学 pug 1s 不是很明白……

OVO

再

~~这个人怎么这么啰嗦~~

现在这个全白的 ico 对于亮色模式极其诡异，标签页切过去就莫得了……

**Comment by Yue-plus** [comment]
@ToUNVRSe

**Comment by Yue-plus** [comment]
@ToUNVRSe

**Comment by Yue-plus** [comment]
@ToUNVRSe 
如果想不显示备案号的话，可以修改 [`_config.arknights.yml`](https://github.com/Yue-plus/hexo-theme-arknights/blob/hexo/_config.arknights.yml) 删除不要的：

```diff
 aside:
   copyright: # 版权声明、备案号等
     ©: 1970 to 2020
-    ICP: 赣ICP备19008355号
```

另外，另外选项卡上的那个图标我试过改成灰的或者加描边都不是很好看……So……

**Comment by Yue-plus** [comment]
如果想自定义选项卡上的图标的话，可以修改主题目录下的 [`/source/favicon.ico`](https://github.com/Yue-plus/hexo-theme-arknights/blob/master/source/favicon.ico) 文件。

搜个在线 ico 图标转换器，转换成 32*32 大小的换上去。

**Comment by ToUNVRSe** [comment]
@Yue-plus 图案的问题晓得

其实备案号的话，删一个没问题，全删了就锅了……暴风级指针问题……

~~天晓得是不是指针~~

~~哇，我为什么要为我没定义的东西负责啊，噢，这不是 STL 容器啊，那没事了~~

**Comment by Yue-plus** [comment]
@ToUNVRSe 
更新了，可在主题目录下执行 `git pull` 更新主题。

现在可将 [`_config.arknights.yml`](https://github.com/Yue-plus/hexo-theme-arknights/blob/hexo/_config.arknights.yml) 中的 `copyright` 设为 `null` 不显示版权信息：

```diff
 aside:
-  copyright: # 版权声明、备案号等
-    ©: 1970 to 2020
-    ICP: 赣ICP备19008355号
+  copyright: null
```

------

是我没做空安全 Orz

**Comment by ToUNVRSe** [comment]
@Yue-plus ⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄

不是很明白但假装明白了

**Comment by ToUNVRSe** [comment]
@Yue-plus Bug

归档只能显示十篇

然后……然后就没有了 OAO

**Comment by Yue-plus** [comment]
@ToUNVRSe 已修复，可在主题目录下执行 `git pull` 更新主题。

加了个翻页器：

![QQ截图20210724072742](https://user-images.githubusercontent.com/33195150/126850162-485c01e1-0dd7-45a5-abc7-b6deeaa74407.jpg)

如果想一页显示完可以修改 Hexo 目录下的 `_config.yml` 文件（大概在第 89 行）：

```diff
 # Pagination
 ## Set per_page to 0 to disable pagination
-per_page: 10
+ per_page: 0
 pagination_dir: page
```

示例：

![QQ截图20210724072812](https://user-images.githubusercontent.com/33195150/126850282-fe920146-ec2b-412c-82d7-cd5378723d91.jpg)

**Comment by ToUNVRSe** [comment]
OVO
