### ISSUE TITLE
Readme部署错误

### ISSUE THREAD

**Issue by SherkeyXD** [Yue-plus/hexo-theme-arknights#33]
如图Readme.md被转换为html时格式错误
![IMG_20211219_184653_784](https://user-images.githubusercontent.com/57581480/146672475-8bb0db84-f92d-46f5-aa6e-6c230454131c.jpg)

**Comment by SherkeyXD** [comment]
顺带问一下为什么进入文章页面后侧边栏字体会变？

**Comment by Yue-plus** [comment]
> 如图Readme.md被转换为html时格式错误 ![IMG_20211219_184653_784](https://user-images.githubusercontent.com/57581480/146672475-8bb0db84-f92d-46f5-aa6e-6c230454131c.jpg)

这是一个已知问题，参考 [Hexo 配置 - 包括或不包括目录和文件](https://hexo.io/zh-cn/docs/configurationconfiguration#包括或不包括目录和文件)。

Hexo 貌似会先读取主题目录和 Hexo 目录下的 `source` 文件夹中的所有内容，然后将所有 `.md` 文件转换为 `.html`

Orz

**Comment by Yue-plus** [comment]
> 顺带问一下为什么进入文章页面后侧边栏字体会变？

我这边没有这个问题，我认为应该是你那边网速较慢导致的。

可否提供一下 **开发者工具** -> **网络** 截图？

例如：![QQ截图20211226205448](https://user-images.githubusercontent.com/33195150/147408773-b5fcc500-0f2d-45fa-b02a-76e07b2ad483.jpg)

**Comment by SherkeyXD** [comment]
> > 顺带问一下为什么进入文章页面后侧边栏字体会变？
> 
> 我这边没有这个问题，我认为应该是你那边网速较慢导致的。
> 
> 可否提供一下 **开发者工具** -> **网络** 截图？
> 
> 例如：![QQ截图20211226205448](https://user-images.githubusercontent.com/33195150/147408773-b5fcc500-0f2d-45fa-b02a-76e07b2ad483.jpg)

最近没摸电脑，看不了F12www
但是在平板上看到的字体样式也不一样（网络不一样）

**Comment by Yue-plus** [comment]
> > > 顺带问一下为什么进入文章页面后侧边栏字体会变？
> > 
> > 我这边没有这个问题，我认为应该是你那边网速较慢导致的。
> > 
> > 可否提供一下 **开发者工具** -> **网络** 截图？
> > 
> > 例如：![QQ截图20211226205448](https://user-images.githubusercontent.com/33195150/147408773-b5fcc500-0f2d-45fa-b02a-76e07b2ad483.jpg)
> 
> 最近没摸电脑，看不了F12www
> 但是在平板上看到的字体样式也不一样（网络不一样）

可否提供一下已部署的网站链接？

**Comment by SherkeyXD** [comment]
> > > > 顺带问一下为什么进入文章页面后侧边栏字体会变？
> > > 
> > > 
> > > 我这边没有这个问题，我认为应该是你那边网速较慢导致的。
> > > 可否提供一下 **开发者工具** -> **网络** 截图？
> > > 例如：![QQ截图20211226205448](https://user-images.githubusercontent.com/33195150/147408773-b5fcc500-0f2d-45fa-b02a-76e07b2ad483.jpg)
> > 
> > 
> > 最近没摸电脑，看不了F12www
> > 但是在平板上看到的字体样式也不一样（网络不一样）
> 
> 可否提供一下已部署的网站链接？

sherkeyxd.github.io
是不是没有cdn的关系？

**Comment by Yue-plus** [comment]
> > > > > 顺带问一下为什么进入文章页面后侧边栏字体会变？
> > > > 
> > > > 
> > > > 我这边没有这个问题，我认为应该是你那边网速较慢导致的。
> > > > 可否提供一下 **开发者工具** -> **网络** 截图？
> > > > 例如：![QQ截图20211226205448](https://user-images.githubusercontent.com/33195150/147408773-b5fcc500-0f2d-45fa-b02a-76e07b2ad483.jpg)
> > > 
> > > 
> > > 最近没摸电脑，看不了F12www
> > > 但是在平板上看到的字体样式也不一样（网络不一样）
> > 
> > 
> > 可否提供一下已部署的网站链接？
> 
> [sherkeyxd.github.io](https://sherkeyxd.github.io/) 是不是没有cdn的关系？

可以确定不是网络问题；

请在主题目录下执行 `git pull` 更新主题试试？
或者参考 [README.md#手动安装](https://github.com/Yue-plus/hexo-theme-arknights#手动安装) 重新新建一个 Hexo 目录试试？

**Comment by SherkeyXD** [comment]
重新构建后问题解决，感谢
