### ISSUE TITLE
请问如何修改页面的背景图片？

### ISSUE THREAD

**Issue by Guda-nemo** [Yue-plus/hexo-theme-arknights#34]
您好，请问有什么办法可以自定义背景图片吗，我尝试改动css文件但网页打开会是一片空白

**Comment by feilongproject** [comment]
请确保：
1. 图片链接可以正常访问，且没有referer访问限制
2. sass格式正常，并且修改的是`themes/arknights/source/css/sass/_base_style.sass`文件

另：提交issue时最好附上具体文件（比如修改了那个文件后才开始出现异常）

**Comment by Yue-plus** [comment]
已更新主题，请在本地主题目录下执行 `git pull` 更新主题。

现在可以修改 Hexo 目录下的 `_config.arknights.yml` 文件定义 `<body>` 的背景图片：

```yaml
# <body> 背景图片链接
background_image: https://ak.hypergryph.com/assets/index/images/ak/pc/bk.jpg # /img/bg.jpg
```
