### ISSUE TITLE
希望增加代码块一键复制功能，以及代码块渲染的一个问题。

### ISSUE THREAD

**Issue by RWoxiN** [Yue-plus/hexo-theme-arknights#38]
如题

在代码块添加在列表后面的时候，无法正确渲染。即 `* ```dos \n ... \n ``` ` 时，无法正确识别 `*` 后面的 ` ``` `。

比如下图情况，这段 md 直接复制到 hexo 时，会出现渲染错误。

本地编辑器预览：
![image](https://user-images.githubusercontent.com/78133217/152163446-41f6a615-cb9e-424a-8a39-fad031ef04af.png)

Markdown 文本：
![image](https://user-images.githubusercontent.com/78133217/152163660-7d45d8da-7206-49ca-9ed4-8f6a071b875e.png)

hexo 预览：
![image](https://user-images.githubusercontent.com/78133217/152163818-a1148e06-7857-4bed-8474-9b8836bf093c.png)

**Comment by Yue-plus** [comment]
刚刚成功复现了这个bug：

![image](https://user-images.githubusercontent.com/33195150/152494121-db47e857-0591-4759-acd8-596f02efe50b.png)

但这其实这是 Hexo 默认渲染器 `hexo-renderer-marked` 的一个“特性”。
你需要在每个列表项上下都加一个空行，如下图红箭头处：

![image](https://user-images.githubusercontent.com/33195150/152494437-06653dd7-da44-4d84-b6f2-bbfec42874a9.png)

**Comment by Yue-plus** [comment]
可以考虑将默认渲染器 `hexo-renderer-marked` 更换为 [**`hexo-renderer-markdown-it`**](https://github.com/hexojs/hexo-renderer-markdown-it) 可以解决渲染错误的问题：

![image](https://user-images.githubusercontent.com/33195150/152496146-b10155f4-0047-4e1c-a278-fd81b0189513.png)

**Comment by Yue-plus** [comment]
@ToUNVRSe 已实现代码块一键复制，等待 PR 中……

![5KU{0A6M6F CEG8M MHJOU](https://user-images.githubusercontent.com/33195150/152498387-7b9f1f50-37e3-433f-b88b-5ff131347ab7.jpg)

**Comment by RWoxiN** [comment]
> 可以考虑将默认渲染器 `hexo-renderer-marked` 更换为 [**`hexo-renderer-markdown-it`**](https://github.com/hexojs/hexo-renderer-markdown-it) 解决渲染错误的问题：
> 
> ![image](https://user-images.githubusercontent.com/33195150/152496146-b10155f4-0047-4e1c-a278-fd81b0189513.png)

其实 `hexo-renderer-markdown-it` 的渲染也是错的。只能先这样了，把 `*` 去掉，直接当个父序号下的缩进段落还好看点。
