### ISSUE TITLE
vercel构建出错

### ISSUE THREAD

**Issue by webyang-male** [Yue-plus/hexo-theme-arknights#44]
![image](https://user-images.githubusercontent.com/52821367/152821539-013e3b6f-53e2-4e90-999a-289d848c914b.png)
请问如何处理

**Comment by Yue-plus** [comment]
请问是在主题 `1.14.0` 之前创建的项目吗？

请将 `package.json` 文件贴上来。

------------------------------------------

也可以尝试以下方法：

1. 删除：
   - Hexo 目录下的 `node_modules`  文件夹
   - Hexo 目录下的 `themes/arknights` 文件夹，并重新 clone 主题。
2. 检查 Hexo 版本（需要 `6.0.0` 以上）
3. 移除 `hexo-renderer-sass`；安装 `hexo-renderer-dartsass`
4. 重新安装依赖包

**Comment by webyang-male** [comment]
> 请问是在主题 `1.14.0` 之前创建的项目吗？
> 
> 请将 `package.json` 文件贴上来。
> 
> 也可以尝试以下方法：
> 
> 1. 删除：
>    
>    * Hexo 目录下的 `node_modules`  文件夹
>    * Hexo 目录下的 `themes/arknights` 文件夹，并重新 clone 主题。
> 2. 检查 Hexo 版本（需要 `6.0.0` 以上）
> 3. 移除 `hexo-renderer-sass`；安装 `hexo-renderer-dartsass`
> 4. 重新安装依赖包

感谢作者大大,确认是`package.json`依赖包的问题,直接复制你的hexo分支中的依赖文件好了
