### ISSUE TITLE
增加字数统计和阅读时长

### ISSUE THREAD

**Issue by webyang-male** [Yue-plus/hexo-theme-arknights#55]
1. 文章页显示字数和阅读时长(阅读时长相比不那么重要,能加上更好)
2. 博客侧边栏可也加上全站字数
以上效果图类似如下:
![image](https://user-images.githubusercontent.com/52821367/155835897-6d04e16e-5373-49e0-ac58-ea8df93aaf3c.png)
![image](https://user-images.githubusercontent.com/52821367/155835913-fd3c21b4-847c-42bf-92f5-6be9acb4f5fe.png)

**Comment by Yue-plus** [comment]
亲，这边建议您换个带后端的博客系统



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月26日(周六) 下午4:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Yue-plus/hexo-theme-arknights] 增加字数统计和阅读时长 (Issue #55)




  
文章页显示字数和阅读时长(阅读时长相比不那么重要,能加上更好) 

博客侧边栏可也加上全站字数
 以上效果图类似如下:

**Comment by webyang-male** [comment]
> 亲，这边建议您换个带后端的博客系统（233333
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2022年2月26日(周六) 下午4:18
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.***&gt;;
> 主题: [Yue-plus/hexo-theme-arknights] 增加字数统计和阅读时长 (Issue #55)
> 
> 
> 
> 
>   
> 文章页显示字数和阅读时长(阅读时长相比不那么重要,能加上更好) 
> 
> 博客侧边栏可也加上全站字数
>  以上效果图类似如下:
>  
>   
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

不许寄!别的主题有的你也要有。（doge
