### ISSUE TITLE
建议备案设置为null时直接不显示这一条

### ISSUE THREAD

**Issue by SherkeyXD** [Yue-plus/hexo-theme-arknights#57]
~有点丑（~
话说我记得之前设置成null就是不显示的啊，为什么现在还是会留一个空白的框呢

**Comment by Yue-plus** [comment]
把 icp: 那一行删了就不显示了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月27日(周日) 晚上8:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Yue-plus/hexo-theme-arknights] 建议备案设置为null时直接不显示这一条 (Issue #57)




 
有点丑（
 话说我记得之前设置成null就是不显示的啊，为什么现在还是会留一个空白的框呢

**Comment by Yue-plus** [comment]
> 把 icp: 那一行删了就不显示了。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年2月27日(周日) 晚上8:04 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [Yue-plus/hexo-theme-arknights] 建议备案设置为null时直接不显示这一条 (Issue #57) 有点丑（ 话说我记得之前设置成null就是不显示的啊，为什么现在还是会留一个空白的框呢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

修改 Hexo 目录下的 `_config.arknights.yml` 文件：

```diff
 # 右侧边栏
 aside:
   in_left: false # 侧边栏在左 true / false
   logo: https://ak.hypergryph.com/assets/index/images/ak/pc/faction/1.png #图片链接，建议 1:1 比例
   dr: https://github.com/Yue-plus # 侧边栏 Dr. 链接
   block_in_top: false # 目前为侧边栏文章目录置顶
   copyright: # 版权声明、备案号等，可自定义键值，不想显示则留空
     ©: 1970 to 2020
-    ICP: 赣ICP备19008355号
```
