### ISSUE TITLE
斜体字体未使用jetbrains mono

### ISSUE THREAD

**Issue by SherkeyXD** [Yue-plus/hexo-theme-arknights#59]
如图
![IMG_20220228_223911_285.JPG](https://user-images.githubusercontent.com/57581480/156001934-2f032757-eec5-43ec-b2c1-04aacb0d165e.JPG)
使用英文也一样，所以应该不是中文的问题

顺带还想问一下为什么网页标题前面有个竖着的杠杠，_config.yml里面没有这东西啊 ![IMG_20220228_224043_325.JPG](https://user-images.githubusercontent.com/57581480/156002201-ee815993-1a22-436a-9023-74ba2df317ba.JPG)

**Comment by ToUNVRSe** [comment]
斜体字不知道
这个 `|` 是用于 subtitle 的，上次注意到了但是忘改了。
谢罪

**Comment by SherkeyXD** [comment]
> 斜体字不知道
> 这个 `|` 是用于 subtitle 的，上次注意到了但是忘改了。
> 谢罪

想问一下主页怎么设置标签的？我看你博客的主页subtitle是terminal，但是不知道怎么改

**Comment by ToUNVRSe** [comment]
hexo _config 里的 subtitle

**Comment by SherkeyXD** [comment]
问题解决
