### ISSUE TITLE
建议添加侧边进度条和一键回顶

### ISSUE THREAD

**Issue by 983562336** [Yue-plus/hexo-theme-arknights#6]
这样就方便知道浏览到什么位置，也可以快捷的回到顶部

**Comment by Yue-plus** [comment]
已收到反馈；
一键回顶已经有了：
![QQ截图20200722123731](https://user-images.githubusercontent.com/33195150/88134781-22011880-cc18-11ea-992e-2cf05388825d.png)

**Comment by Yue-plus** [comment]
请问您用的什么浏览器？能发张文章页截图来看看吗？

**Comment by 983562336** [comment]
新版Edga

![E)@VF$I~G(J W$3EHNZ7~NC](https://user-images.githubusercontent.com/57127385/88148383-1706b200-cc31-11ea-9cd8-f5c844e45da4.png)

**Comment by Yue-plus** [comment]
这个滚动条是可以拖动的（可能显示效果没这么明显）
![QQ截图20200722154129](https://user-images.githubusercontent.com/33195150/88149113-36520f00-cc32-11ea-8a84-b4ac3232485e.png)
这个滚动条已经可以达到显示阅读进度的目的了，没有必要再做个进度条了。

**Comment by 983562336** [comment]
！！？？这里吗，不认真看还真没看出来

**Comment by Yue-plus** [comment]
23333333
回头试着吧颜色对比调显眼点好了（加宽是真的难看）
