### ISSUE TITLE
页面顶部菜单内容过多之后在竖屏模式下会挡住部分内容

### ISSUE THREAD

**Issue by lensferno** [Yue-plus/hexo-theme-arknights#60]
如题，如下图 

![](http://oss-img.ciduid.top/default/Snipaste_2022-03-21_21-47-06.png)
![](http://oss-img.ciduid.top/default/Snipaste_2022-03-21_22-06-04.png)

我把header的position: fixed去掉之后就不会挡住了，但是header旁边会出现空白，效果不是很好 
前端技术不是很好...也只能做到这一步了...
![](http://oss-img.ciduid.top/default/Snipaste_2022-03-21_22-17-10.png)

希望能改进一下吧 ：）

**Comment by ToUNVRSe** [comment]
上个版本的时候 corner 考虑少了，这次会认真测试的（确信）

**Comment by lensferno** [comment]
> 上个版本的时候 corner 考虑少了，这次会认真测试的（确信）

哈哈，期待完成

**Comment by Yue-plus** [comment]
🚀🚀🚀 [hexo-theme-arknights_1.15.0](https://github.com/Yue-plus/hexo-theme-arknights/releases/tag/1.15.0) 已发布！
快来试试新版本~
