### ISSUE TITLE
动态背景设置了true但是依然是静态背景

### ISSUE THREAD

**Issue by heijijiji** [Yue-plus/hexo-theme-arknights#66]
1.动态背景设置了true但是依然是静态背景
2.hexo g出现如图所示的报错
![image](https://user-images.githubusercontent.com/84003116/160142123-c98c8b5e-7d74-4da7-b6d6-46b915b3afd5.png)
呜呜，纯小白，求大佬指点

**Comment by ToUNVRSe** [comment]
问题二：如果您需要字数/阅读时长统计，请参考 README 安装依赖项

问题一：在页面中按一下 F12 并截图发一下，方便远程调试（

**Comment by heijijiji** [comment]
![image](https://user-images.githubusercontent.com/84003116/160144240-c7f92d5d-9d05-41ad-a028-bb92aa29baa1.png)
请问是需要这个么？

**Comment by ToUNVRSe** [comment]
阿西，Yue_plus 忘了放编译文件。
您可以选择装一个 hexo-renderer-ts（可能会产生无意义警告）
也可以选择我发一份（

**Comment by heijijiji** [comment]
嘶，我用”npm install hexo-renderer-ts“(不知道对不对)安装了，然后鼠标的动画有了，但是背景动画还是没有，然后出现了以下报错：
![image](https://user-images.githubusercontent.com/84003116/160146781-d10c3e16-c66e-4505-974e-e1e55c47d0a2.png)
![image](https://user-images.githubusercontent.com/84003116/160146850-5461a68b-d4e7-4631-96ee-cd3f1d293e90.png)
