### ISSUE TITLE
请问如何去掉右下角的版权信息？

### ISSUE THREAD

**Issue by SuWeizhe1124** [Yue-plus/hexo-theme-arknights#7]
published with Hexo Theme Arknight by Yue_plus 這一段怎麼拿掉 ，就首頁右下角

**Comment by Yue-plus** [comment]
修改 `<hexo>/themes/arknights/layout/includes/layout.pug` 文件
删除第 62 ~ 69 行
> 虽然还是很希望能留着这一行 `/(ㄒoㄒ)/~~`
