### ISSUE TITLE
本地local显示正常，但发布到github page却显示不正常

### ISSUE THREAD

**Issue by P0etry-rain** [Yue-plus/hexo-theme-arknights#71]
![hexo_error](https://user-images.githubusercontent.com/52886465/162693853-94040a7a-6c74-470f-8aa6-b2e28a1ba753.png)
![local](https://user-images.githubusercontent.com/52886465/162693856-f99df9b7-1971-4b3b-8a8c-04256ac01138.png)

**Comment by ToUNVRSe** [comment]
像送葬人一样精准无情的人工智能 ToUNVRSe 为您解答。

诊断结果：

- 错误原因：疑似没有 CSS 文件。

- 导致错误的原因：未知

- 下一步：在页面中按一下 F12 并截图发一下，方便远程调试

![error](https://user-images.githubusercontent.com/60533323/162694572-6b615f5c-967f-4553-bae8-3311f5936585.jpg)

**Comment by P0etry-rain** [comment]
![f12-html](https://user-images.githubusercontent.com/52886465/162695891-ee1a2ead-19e5-4f9c-a738-19dfa6d050ed.png)
![f12-html2](https://user-images.githubusercontent.com/52886465/162695899-4664e5db-a77d-4344-8f6f-424b82a04e2e.png)

**Comment by ToUNVRSe** [comment]
> ToUNVRSe 检测到了火狐浏览器，ToUNVRSe 想到了不好的事情

需要：控制台信息

**Comment by P0etry-rain** [comment]
![console](https://user-images.githubusercontent.com/52886465/162697375-55104016-45bd-4dfc-b85c-0f64c980e835.png)

**Comment by Yue-plus** [comment]
试试修改 **Hexo 目录下的** [`_config.yml`](https://github.com/Yue-plus/hexo-theme-arknights/blob/e5199f9025ea43ad83806877464e9d9e69221da7/_config.yml#L17) 文件 第 17 行附近：

```diff
- root: /
+ root: /bolg/
```

**Comment by P0etry-rain** [comment]
> 试试修改 **Hexo 目录下的** [`_config.yml`](https://github.com/Yue-plus/hexo-theme-arknights/blob/e5199f9025ea43ad83806877464e9d9e69221da7/_config.yml#L17) 文件 第 17 行附近：
> 
> ```diff
> - root: /
> + root: /blog/
> ```
好的 我试试

**Comment by P0etry-rain** [comment]
> 试试修改 **Hexo 目录下的** [`_config.yml`](https://github.com/Yue-plus/hexo-theme-arknights/blob/e5199f9025ea43ad83806877464e9d9e69221da7/_config.yml#L17) 文件 第 17 行附近：
> 
> ```diff
> - root: /
> + root: /blog/
> ```

似乎没有什么效果 修改目录后页面为404

**Comment by P0etry-rain** [comment]
> 可以尝试：
> 
> 1. 还原之前的操作（可能需要）
> 2. 更改 Hexo 目录下的 [_config.yml](https://github.com/Yue-plus/hexo-theme-arknights/blob/e5199f9025ea43ad83806877464e9d9e69221da7/_config.yml#L74) 文件 第 74 行附近：
> 
> ```diff
> index_generator:
> -   path: ''
> +   path: 'blog'
> ```
修改后为404报错
![blog](https://user-images.githubusercontent.com/52886465/162703187-fce1d15d-98e6-4409-8984-0742fba252f7.png)

**Comment by ToUNVRSe** [comment]
如果这是本地结果，那么 localhost:4000/blog 应该就是正常页面了

**Comment by P0etry-rain** [comment]
> 如果这是本地结果，那么 localhost:4000/blog 应该就是正常页面了

这个是github page的结果，localhost:4000/blog确实是正常页面。但page页面https://p0etry-rain.github.io/blog/显示为上图

**Comment by P0etry-rain** [comment]
解决完了 目录的问题
