### ISSUE TITLE
右侧的Archives Total和Dr.XXX没有返回设定的根目录

### ISSUE THREAD

**Issue by fzy1000** [Yue-plus/hexo-theme-arknights#8]
您好，我设定的根目录为https://xxxxxx.github.io/blog.io/   .所以点击header里面的achieves会跳转到https://xxxxxx.github.io/blog.io/archives/  .但是右侧的Archives Total点击后会跳转到https://xxxxxx.github.io/archives/  。然后点击Dr.XXX也没有返回根目录https://xxxxxx.github.io/blog.io/  而是跳转到了https://xxxxxx.github.io/

**Comment by Yue-plus** [comment]
感谢，您的反馈。现在已经紧急修复了这个 bug。
请在主题目录下执行 `git pull` 来更新主题。

现在，右侧的 Archives Total 回跳转到 `<Hexo>/_config.yml` 设置的根目录。
而，`Dr.` 的转跳目标可以在  `<Hexo>/themes/arknights/_config.yml` 中自由设置（第 10 行）。

**Comment by fzy1000** [comment]
感谢！

**Comment by Yue-plus** [comment]
现在子目录部署，CSS、JS、赞助二维码等都会根据  `<Hexo>/_config.yml` 中设置的根路径计算了。
