### ISSUE TITLE
markdown在标题前没有空行可能导致奇怪的缩进

### ISSUE THREAD

**Issue by what-is-me** [Yue-plus/hexo-theme-arknights#80]
# markdown在标题前没有空行可能导致奇怪的缩进
形如：
```markdown
- a
- b
# title
```
会导致title被缩进，大概是这个样子的，并且会造成目录等的混乱![屏幕截图2022-06-11](https://user-images.githubusercontent.com/70659394/173186002-855a4663-218c-4298-868b-23133e49ed01.png)
而
```markdown
- a
- b

# title
```

不会导致title被缩进。

vs-code里有个叫markdown-formatter的插件会格式化成第一种情况，markdown all in one不会进行改动，prettier-code formater则会格式化为第二种情况。

我用的是较老版本的主题（2022年2月左右的），如果该问题已经被解决，请关闭或者删除此issue，谢谢。

**Comment by Yue-plus** [comment]
这是 Hexo 默认渲染器（`hexo-renderer-marked`）的“特性”：

```markdown
- item1
- item2
# 这会被认为是 item2 中的内容
- item3
```

![image](https://user-images.githubusercontent.com/33195150/173186676-59ff3637-534d-4d7f-bbda-3d3e17fec0b9.png)

可以考虑更换 Hexo 渲染器，例如：

- [`hexo-renderer-markdown-it`](https://github.com/hexojs/hexo-renderer-markdown-it)
- [`hexo-renderer-pandoc`](https://github.com/wzpan/hexo-renderer-pandoc)
- 也可以在 [Hexo 官网中搜索插件](https://hexo.io/plugins/)，关键字：`renderer`
