### ISSUE TITLE
关于Wiki

### ISSUE THREAD

**Issue by arkerny** [Yue-plus/hexo-theme-arknights#87]
建议为本项目写一个wiki，readme文件过于杂乱，我正在写大部分，望加入开发：
<https://github.com/arkerny/hexo-theme-arknights>
<https://github.com/arkerny/hexo-theme-arknights/wiki/>

**Comment by arkerny** [comment]
目前修改了Readme文件，添加了项目Wiki

**Comment by Yue-plus** [comment]
![%V4GQLJ}LRX8USH1{D 5@HL](https://user-images.githubusercontent.com/33195150/179353676-bbe92f8e-f0d7-46d5-af72-c0668e2a8523.gif)

**Comment by arkerny** [comment]
所以大佬给个权限？

**Comment by arkerny** [comment]
或者推荐大佬组织一个团队来进行开发

**Comment by Yue-plus** [comment]
已邀请成为协作者

-------------------------------------

团队想过，但感觉自己没啥领导能力

![XP53ITHDSBHG`$8I2CULI{K](https://user-images.githubusercontent.com/33195150/179354853-ecb28ca0-e5fb-4313-83ca-2559c822c28b.png)
